#[test_only]
/// End-to-end attestation tests for reef::registry::register_derivative_attested.
///
/// Test vectors generated by scripts/gen-attest-vectors.mjs using a
/// deterministic Ed25519 keypair (seed = 32 bytes of 0x07).
///
/// Signed bytes = BCS(IntentMessage<ComputeResultPayload>):
///   intent(u8=0) ++ timestamp_ms(u64 LE) ++ bcs(ComputeResultPayload{dataset_id, algo_hash, metrics})
module reef::attest_tests;

use reef::enclave;
use reef::registry::{Self, REEF};
use sui::test_scenario as ts;

// ---- deterministic test vectors (from scripts/gen-attest-vectors.mjs) ----

// Ed25519 public key for seed = 0x07 * 32
const PK: vector<u8> = x"ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c";

// dataset_id = 32 bytes of 0xab (used as the parent object ID bytes)
const DATASET_ID: vector<u8> = x"abababababababababababababababababababababababababababababababab";

// algo_hash = utf8("sha256:mean-aggregate")
const ALGO_HASH: vector<u8> = x"7368613235363a6d65616e2d616767726567617465";

// metrics = utf8('{"columnMeans_0":3,"n":5}')
const METRICS: vector<u8> = x"7b22636f6c756d6e4d65616e735f30223a332c226e223a357d";

// timestamp_ms = 1717000000000
const TIMESTAMP_MS: u64 = 1717000000000;

// Raw 64-byte Ed25519 signature over BCS(IntentMessage<ComputeResultPayload>)
const SIG: vector<u8> = x"f61fe37b348003251ddbec8c0d2b45deb6d18ae461ac49eeed23b532812215dc07519492904ed439553b04f8944ebf410ff2c5cd79150b6b250488c38bfc9403";

// ---- test addresses ----
const CALLER: address = @0xC0DE;

// ---- tests ----

#[test]
/// A valid enclave signature MUST be accepted: register_derivative_attested
/// must not abort and must create the derivative artifact.
fun attested_registration_accepts_valid_signature() {
    let mut sc = ts::begin(CALLER);

    // Build the enclave object backed by our deterministic public key.
    let enclave = enclave::new_enclave_for_testing<REEF>(PK, sc.ctx());

    // Construct a parent ID from the same 32 bytes we signed as dataset_id.
    let parent = object::id_from_bytes(DATASET_ID);

    // Call the attested registration — MUST NOT abort.
    registry::register_derivative_attested(
        0,           // tier = public
        0,           // price
        parent,
        option::none<sui::object::ID>(),
        &enclave,
        TIMESTAMP_MS,
        ALGO_HASH,
        METRICS,
        SIG,
        sc.ctx(),
    );

    enclave::destroy(enclave);
    sc.end();
}

#[test]
#[expected_failure(abort_code = 100, location = reef::registry)] // 100 = reef::registry::EBadEnclaveSig
/// A bad (all-zero) signature MUST be rejected with EBadEnclaveSig (= 100).
fun attested_registration_aborts_on_bad_signature() {
    let mut sc = ts::begin(CALLER);

    let enclave = enclave::new_enclave_for_testing<REEF>(PK, sc.ctx());
    let parent  = object::id_from_bytes(DATASET_ID);

    // 64 zero bytes — guaranteed invalid signature.
    let bad_sig = x"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    // MUST abort with EBadEnclaveSig = 100.
    registry::register_derivative_attested(
        0,
        0,
        parent,
        option::none<sui::object::ID>(),
        &enclave,
        TIMESTAMP_MS,
        ALGO_HASH,
        METRICS,
        bad_sig,
        sc.ctx(),
    );

    enclave::destroy(enclave);
    sc.end();
}
